  email:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download summary artifact
        uses: actions/download-artifact@v4
        with:
          name: summary-file

      - name: Send summary email
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "OpenAlex Weekly Summary"
          to: "jdebuck@ucalgary.ca"
          from: "${{ secrets.MAIL_USERNAME }}"
          html_body: |
            <p>The latest OpenAlex Weekly Summary has been generated.</p>
            <p>View it on GitHub Pages: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/</p>
          attachments: |
            summary_latest.html
